version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @angular/cli@9.0.6
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --prod
      - s3folder=$(echo $CODEBUILD_SOURCE_VERSION | cut -d "/" -f 2)
      - echo $CODEBUILD_SOURCE_VERSION
      - aws s3api head-object --bucket vb-urls-3bucket-test-experation-time --key automation_last_commit
      - aws s3 cp s3://ci-pipelinebucket-5urq49af63w/${s3folder}/automation_last_commit . --recursive
      #- last_commit=$(cat automation_last_commit)
      - aws s3 cp s3://vb-urls-3bucket-test-experation-time/${s3folder}:${last_commit}  s3://vb-urls-3bucket-test-experation-time/VBsmoke-test-two/SourceArti/${last_commit} --recursive --exclude "*" --force-glacier-transfer --debug --key automation_last_commit
      #- $(echo last_commit)
      - aws s3 ls s3://ci-pipelinebucket-5urq49af63w/${s3folder} --recursive --human-readable
      #- kubernetes-run automation staging --template=smoke-runner --image=271332529381.dkr.ecr.eu-west-1.amazonaws.com/automation:${last_commit} make smoke-test
    finally:
      - echo final block echo

artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
